services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/jwt_authentication/db:/docker-entrypoint-initdb.d

  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: